export const TYPE_OF_EVENTS = {
  TODAY: "TODAY",
  HOLIDAY: "HOLIDAY",
  BIRTHDAY: "BIRTHDAY",
  BUSY: "BUSY",
  ANNIVERSARY: "ANNIVERSARY"
};

export const TYPE_OF_CHANGE_YEAR = {
  TO_PREVIOUS_YEAR: "TO_PREVIOUS_YEAR",
  TO_NEXT_YEAR: "TO_NEXT_YEAR"
};