export const TYPE_OF_EVENTS = {
  NOTHING_SPECIAL: "NOTHING_SPECIAL",
  HOLIDAY: "HOLIDAY",
  BIRTHDAY: "BIRTHDAY",
  BUSY: "BUSY",
  ANNIVERSARY: "ANNIVERSARY"
};

export const TODAY = "TODAY";

export const TYPE_OF_CHANGE_YEAR = {
  TO_PREVIOUS_YEAR: "TO_PREVIOUS_YEAR",
  TO_NEXT_YEAR: "TO_NEXT_YEAR"
};

export const DAYS_IN_WEEK = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY"
};

export const MONTHS = {
  JANUARY: "JANUARY",
  FEBRUARY: "FEBRUARY",
  MARCH: "MARCH",
  APRIL: "APRIL",
  MAY: "MAY",
  JUNE: "JUNE",
  JULY: "JULY",
  AUGUST: "AUGUST",
  SEPTEMBER: "SEPTEMBER",
  OCTOBER: "OCTOBER",
  NOVEMBER: "NOVEMBER",
  DECEMBER: "DECEMBER"
};

export const MONTHS_LIST = [
  "JANUARY",
  "FEBRUARY",
  "MARCH",
  "APRIL",
  "MAY",
  "JUNE",
  "JULY",
  "AUGUST",
  "SEPTEMBER",
  "OCTOBER",
  "NOVEMBER",
  "DECEMBER"
];
